### ISSUE TITLE
Can no longer compile in a non-X11 environment

### ISSUE THREAD

**Issue by AdamWRichardson** [RTimothyEdwards/magic#150]
I can no longer compile magic as of commit `6947b8c6d7af1cdaa629f3f53a16dec02b71533b` which introduced changes when configuring without Xorg. Even though all dependencies are installed when I run `./configure --without-x` the configure script fails to find the cario, tcl and Tk headers as well as X11 graphics.

A proper build system like CMake would make identifying these things easier, as well as unittests and CI which are currently not implemented.

**Comment by RTimothyEdwards** [comment]
It's not a matter of the make environment.  It's a matter of the fact that previously, compiling "without X" did not actually compile without X.  That being fixed in the configuration, it is now surfacing actual errors in the code where X routines are being compiled into parts of the code that are not graphics-dependent.  These will need to be fixed.

**Comment by AdamWRichardson** [comment]
Can confirm that I can now build magic again, thank you!
