### ISSUE TITLE
Import of GDS failed.

### ISSUE THREAD

**Issue by JakobRat** [RTimothyEdwards/magic#242]
Hi,
I imported a GDS file into magic but unfortunately the poly-layer wasn't imported correctly.

![Magic_vs_Klayout](https://user-images.githubusercontent.com/74247834/237045573-6809bea5-23f7-4973-a5aa-b3496dcbdb4b.jpg)

You can see the difference by the selected instances in the right part of the figure. 

[GDS_Error.zip](https://github.com/RTimothyEdwards/magic/files/11429208/GDS_Error.zip)

**Comment by RTimothyEdwards** [comment]
@JakobRat :  You probably have a PDK from the brief period where the polysilicon import was screwed up (sadly, the worst errors posted for the shortest time are the ones that manage to get propagated everywhere---Murphy's Law, I suppose).  The issue was introduced in PDK (open_pdks) version 1.0.406 and corrected in PDK version 1.0.407 (the next day!).

**Comment by JakobRat** [comment]
@RTimothyEdwards  Thank you! That's exactly the case.
