### ISSUE TITLE
Device menu not appearing in magic with skywater pdk

### ISSUE THREAD

**Issue by aakash-ics** [RTimothyEdwards/magic#79]
Hi, 

I am trying to use the skywater 130nm open-pdk with magic. Seeing some tutorials/videos about using magic and skywater 130nm I realized that I am not able to see the devices menu of magic. 

SO I found out a file sky130A.tcl which seem to be the device generator menu so I tried sourcing it from the console of magic.

I tried opening magic  inside the ~/open_pdks/sky130/sky130A/libs.tech/magic directory using the following statement in terminal

magic -T sky130A.tech sky130A.tcl 

![image](https://user-images.githubusercontent.com/85435384/120919626-30450f80-c6d8-11eb-9e70-5f22fba2b230.png)

The above image is my case.

![image](https://user-images.githubusercontent.com/85435384/120919845-54edb700-c6d9-11eb-992b-f703b027067b.png)

this image above is one of tutorial that I saw on youtube using magic and sky130.

Also I saw one tutorial from efabless where the person was using magic on the efabless website and there also I could see the devices menu for parameterized device generation.

Kindly help.

Thanks in Advance
Aakash Gupta

**Comment by RTimothyEdwards** [comment]
Sourcing the file like that works for any _new_ windows created;  so if you then did Window->New, the new window would have the device menu.  The Tcl script has to be loaded before the window is created, so it's done in the startup file.  Since the startup file does a number of other important things in addition to loading the device generator script, I recommend doing, e.g., "magic -d OGL -rcfile <path_to>/sky130A/libs.tech/magic/sky130A.magicrc".  The startup script loads the correct tech file, so you don't need the "-T" option on the command line, just the "-rcfile" option.

**Comment by aakash-ics** [comment]
Thanks  RTimothyEdwards,

It worked !

![image](https://user-images.githubusercontent.com/85435384/120929370-6e592800-c706-11eb-8884-c918879562df.png)

**Comment by RTimothyEdwards** [comment]
Unrelated to the PDK, but related to the "-d OGL" argument:  To make the icons on the right show up properly, either use "-d XR" instead of "-d OGL" or else configure with the option "--enable-cairo-offscreen" before compiling.

**Comment by aakash-ics** [comment]
Thanks RTimothyEdwards for the additional information it looks great now!

![image](https://user-images.githubusercontent.com/85435384/120931847-f2b0a880-c710-11eb-9c97-709a5a8f6492.png)
